### ISSUE TITLE
Remove brass plate

### ISSUE THREAD

**Issue by TomGC96** [abersailbot/dewi-hardware#67]
The brass plate reinforcing the rudder pin collar has been affected by water resulting in copper oxide ending up on the deck. 2 screws have also rusted due to them not being stainless steel. These should be removed and replaced.

**Comment by CloudCoppola** [comment]
Do we have a spare brass plate somewhere?

**Comment by TomGC96** [comment]
If we use brass again the same will happen instantly. It's better to use something else.

**Comment by naturesyouth** [comment]
you should switch to an aluminum plate, if you can't find one lying around you can one off ebay for cheap

**Comment by TomGC96** [comment]
Aluminium also corrodes in salt water, although a little less! I'm not sure the plate is the way to go. It might be worth replacing the collar in some way.

**Comment by CloudCoppola** [comment]
Well brass is waterproof so its best to use that and every now and again just clean it. Pete's sanded the plate so it looks brand new and is going to put silicon around the edges.

**Comment by Danyc0** [comment]
What's the point in removing it at all if you're just gonna replace it with another brass one?

**Comment by CloudCoppola** [comment]
Don't need to replace it now. It was really dirty so just had to clean it and attach it back on.

The brass plate has been attached back on, but just needs the two big screws tightly sealed and put silicone on again.

**Comment by Tebazil12** [comment]
Don't forget part of the issue was that the screws arent the right material and rusted, you'll need to find some decent ones to replace them with (probably stainless steal like tom suggested)

**Comment by Tebazil12** [comment]
You might actually want to replace the brass place too btw, brass corrodes in salt water (which is what she'll be sailing in most of the time)

**Comment by Danyc0** [comment]
Really there are two acceptable long-term options:
A. Replace it with a plate of a material which won't rust (good stainless steel, fibreglass, carbon fibre)
B. Remove the fiberglass tube used to attach the rudder (use gloves to avoid the fibreglass problem) and replace it with a new, stronger one, maybe carbon fibre (because obviously the forces on the rudder are too strong for fibreglass, because this is the second one of those tubes to crack on us). It'd need to be attached securely to the transom with fibreglass.

**Comment by TomGC96** [comment]
I was thinking replacing the tube would be the way to go. Something stronger, and make sure it's on straight too!
